

SOCIAL_AUTH_TWITTER_KEY = '0N20oYXidmd6LGJPVVaVXqABT'
SOCIAL_AUTH_TWITTER_SECRET = 'Jo6B9myqtKIyuITG9A0JBKVSiYb6Pqu4NGB3RnCauhICQ5PUyS'


SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
